/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: include/data_type/chassis_data_type.h
  Source: /home/ling/projects/dds_sub/idl/chassis_data_type.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef MYPROJ_INCLUDE_DATA_TYPE_CHASSIS_DATA_TYPE_H_6814039B4794922C08721635F9F25383
#define MYPROJ_INCLUDE_DATA_TYPE_CHASSIS_DATA_TYPE_H_6814039B4794922C08721635F9F25383

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct chassis_data_t
{
  uint8_t data[64];
} chassis_data_t;

extern const dds_topic_descriptor_t chassis_data_t_desc;

#define chassis_data_t__alloc() \
((chassis_data_t*) dds_alloc (sizeof (chassis_data_t)));

#define chassis_data_t_free(d,o) \
dds_sample_free ((d), &chassis_data_t_desc, (o))

typedef struct chassis_simulation_data_t
{
  uint8_t bumper_is_ignore;
  uint8_t ultra_is_enbale;
  uint8_t bat_is_simulate;
  uint8_t charger_is_simulate;
  uint8_t rtk_is_simulate;
} chassis_simulation_data_t;

extern const dds_topic_descriptor_t chassis_simulation_data_t_desc;

#define chassis_simulation_data_t__alloc() \
((chassis_simulation_data_t*) dds_alloc (sizeof (chassis_simulation_data_t)));

#define chassis_simulation_data_t_free(d,o) \
dds_sample_free ((d), &chassis_simulation_data_t_desc, (o))

typedef struct maintain_data_t
{
  double mileage;
  uint32_t work_time;
  uint16_t bat1_cycles;
  uint16_t bat2_cycles;
} maintain_data_t;

extern const dds_topic_descriptor_t maintain_data_t_desc;

#define maintain_data_t__alloc() \
((maintain_data_t*) dds_alloc (sizeof (maintain_data_t)));

#define maintain_data_t_free(d,o) \
dds_sample_free ((d), &maintain_data_t_desc, (o))

typedef struct wheel_pos_data_t
{
  uint16_t wl_sl;
  uint16_t wl_sm;
  uint16_t wl_sr;
  uint16_t wr_sl;
  uint16_t wr_sm;
  uint16_t wr_sr;
} wheel_pos_data_t;

extern const dds_topic_descriptor_t wheel_pos_data_t_desc;

#define wheel_pos_data_t__alloc() \
((wheel_pos_data_t*) dds_alloc (sizeof (wheel_pos_data_t)));

#define wheel_pos_data_t_free(d,o) \
dds_sample_free ((d), &wheel_pos_data_t_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* MYPROJ_INCLUDE_DATA_TYPE_CHASSIS_DATA_TYPE_H_6814039B4794922C08721635F9F25383 */
