/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: include/data_type/custom_data_type.h
  Source: /home/ling/projects/dds_sub/idl/custom_data_type.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef MYPROJ_INCLUDE_DATA_TYPE_CUSTOM_DATA_TYPE_H_D5BCEA68178946B888252BE4CEB8A084
#define MYPROJ_INCLUDE_DATA_TYPE_CUSTOM_DATA_TYPE_H_D5BCEA68178946B888252BE4CEB8A084

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct custom_data_256_t
{
  char value[256];
} custom_data_256_t;

extern const dds_topic_descriptor_t custom_data_256_t_desc;

#define custom_data_256_t__alloc() \
((custom_data_256_t*) dds_alloc (sizeof (custom_data_256_t)));

#define custom_data_256_t_free(d,o) \
dds_sample_free ((d), &custom_data_256_t_desc, (o))

typedef struct custom_data_512_t
{
  char value[512];
} custom_data_512_t;

extern const dds_topic_descriptor_t custom_data_512_t_desc;

#define custom_data_512_t__alloc() \
((custom_data_512_t*) dds_alloc (sizeof (custom_data_512_t)));

#define custom_data_512_t_free(d,o) \
dds_sample_free ((d), &custom_data_512_t_desc, (o))

typedef struct custom_data_1024_t
{
  char value[1024];
} custom_data_1024_t;

extern const dds_topic_descriptor_t custom_data_1024_t_desc;

#define custom_data_1024_t__alloc() \
((custom_data_1024_t*) dds_alloc (sizeof (custom_data_1024_t)));

#define custom_data_1024_t_free(d,o) \
dds_sample_free ((d), &custom_data_1024_t_desc, (o))

typedef struct custom_data_10K_t
{
  char value[10240];
} custom_data_10K_t;

extern const dds_topic_descriptor_t custom_data_10K_t_desc;

#define custom_data_10K_t__alloc() \
((custom_data_10K_t*) dds_alloc (sizeof (custom_data_10K_t)));

#define custom_data_10K_t_free(d,o) \
dds_sample_free ((d), &custom_data_10K_t_desc, (o))

typedef struct custom_data_1M_t
{
  char value[1048576];
} custom_data_1M_t;

extern const dds_topic_descriptor_t custom_data_1M_t_desc;

#define custom_data_1M_t__alloc() \
((custom_data_1M_t*) dds_alloc (sizeof (custom_data_1M_t)));

#define custom_data_1M_t_free(d,o) \
dds_sample_free ((d), &custom_data_1M_t_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* MYPROJ_INCLUDE_DATA_TYPE_CUSTOM_DATA_TYPE_H_D5BCEA68178946B888252BE4CEB8A084 */
