/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: include/data_type/err_info_type.h
  Source: /home/ling/projects/dds_sub/idl/err_info_type.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef MYPROJ_INCLUDE_DATA_TYPE_ERR_INFO_TYPE_H_6C512544AB820109DBEE8137F562BCDB
#define MYPROJ_INCLUDE_DATA_TYPE_ERR_INFO_TYPE_H_6C512544AB820109DBEE8137F562BCDB

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define ERR_CODE_INFO_MAX_LEN 128
typedef enum midware_err_type_e
{
  MIDWARE_ERR_PERCEPTION_TIMEOUT,
  MIDWARE_ERR_INVALID
} midware_err_type_e;

#define midware_err_type_e__alloc() \
((midware_err_type_e*) dds_alloc (sizeof (midware_err_type_e)));

typedef struct error_info_mcu_proxy_t
{
  midware_err_type_e type;
} error_info_mcu_proxy_t;

extern const dds_topic_descriptor_t error_info_mcu_proxy_t_desc;

#define error_info_mcu_proxy_t__alloc() \
((error_info_mcu_proxy_t*) dds_alloc (sizeof (error_info_mcu_proxy_t)));

#define error_info_mcu_proxy_t_free(d,o) \
dds_sample_free ((d), &error_info_mcu_proxy_t_desc, (o))

typedef struct system_error_code_t
{
  int32_t code;
} system_error_code_t;

extern const dds_topic_descriptor_t system_error_code_t_desc;

#define system_error_code_t__alloc() \
((system_error_code_t*) dds_alloc (sizeof (system_error_code_t)));

#define system_error_code_t_free(d,o) \
dds_sample_free ((d), &system_error_code_t_desc, (o))

typedef struct system_power_off_inform_t
{
  int32_t reserve;
} system_power_off_inform_t;

extern const dds_topic_descriptor_t system_power_off_inform_t_desc;

#define system_power_off_inform_t__alloc() \
((system_power_off_inform_t*) dds_alloc (sizeof (system_power_off_inform_t)));

#define system_power_off_inform_t_free(d,o) \
dds_sample_free ((d), &system_power_off_inform_t_desc, (o))

typedef struct perception_error_code_t
{
  double timestamp;
  int32_t status;
} perception_error_code_t;

extern const dds_topic_descriptor_t perception_error_code_t_desc;

#define perception_error_code_t__alloc() \
((perception_error_code_t*) dds_alloc (sizeof (perception_error_code_t)));

#define perception_error_code_t_free(d,o) \
dds_sample_free ((d), &perception_error_code_t_desc, (o))

typedef struct iot_ctrl_t
{
  uint8_t recvDeviceId;
  uint8_t sendDeviceId;
  uint16_t seqs;
  uint16_t datalen;
  int32_t errcode;
  char data[10240];
} iot_ctrl_t;

extern const dds_topic_descriptor_t iot_ctrl_t_desc;

#define iot_ctrl_t__alloc() \
((iot_ctrl_t*) dds_alloc (sizeof (iot_ctrl_t)));

#define iot_ctrl_t_free(d,o) \
dds_sample_free ((d), &iot_ctrl_t_desc, (o))

typedef struct system_event_code_t
{
  int32_t code;
} system_event_code_t;

extern const dds_topic_descriptor_t system_event_code_t_desc;

#define system_event_code_t__alloc() \
((system_event_code_t*) dds_alloc (sizeof (system_event_code_t)));

#define system_event_code_t_free(d,o) \
dds_sample_free ((d), &system_event_code_t_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* MYPROJ_INCLUDE_DATA_TYPE_ERR_INFO_TYPE_H_6C512544AB820109DBEE8137F562BCDB */
