/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: include/data_type/multimedia_type.h
  Source: /home/ling/projects/dds_sub/idl/multimedia_type.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef MYPROJ_INCLUDE_DATA_TYPE_MULTIMEDIA_TYPE_H_2E5919B9E01C766C589B8175DB8041BC
#define MYPROJ_INCLUDE_DATA_TYPE_MULTIMEDIA_TYPE_H_2E5919B9E01C766C589B8175DB8041BC

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct mul_audio_t
{
  int32_t cmd;
} mul_audio_t;

extern const dds_topic_descriptor_t mul_audio_t_desc;

#define mul_audio_t__alloc() \
((mul_audio_t*) dds_alloc (sizeof (mul_audio_t)));

#define mul_audio_t_free(d,o) \
dds_sample_free ((d), &mul_audio_t_desc, (o))

typedef struct mul_led_t
{
  uint8_t red;
  uint8_t green;
  uint8_t blue;
  int32_t udelay;
  int32_t ufrequency;
  int32_t upwm;
} mul_led_t;

extern const dds_topic_descriptor_t mul_led_t_desc;

#define mul_led_t__alloc() \
((mul_led_t*) dds_alloc (sizeof (mul_led_t)));

#define mul_led_t_free(d,o) \
dds_sample_free ((d), &mul_led_t_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* MYPROJ_INCLUDE_DATA_TYPE_MULTIMEDIA_TYPE_H_2E5919B9E01C766C589B8175DB8041BC */
