/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: include/data_type/net_manager_type.h
  Source: /home/ling/projects/dds_sub/idl/net_manager_type.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef MYPROJ_INCLUDE_DATA_TYPE_NET_MANAGER_TYPE_H_E92E6CC35F595B54E4D7DED625DA61FE
#define MYPROJ_INCLUDE_DATA_TYPE_NET_MANAGER_TYPE_H_E92E6CC35F595B54E4D7DED625DA61FE

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum dds_net_type_e
{
  DDS_NET_TYPE_NONE,
  DDS_NET_TYPE_WIFI,
  DDS_NET_TYPE_MNET,
  DDS_NET_TYPE_DEF_MAX_
} dds_net_type_e;

#define dds_net_type_e__alloc() \
((dds_net_type_e*) dds_alloc (sizeof (dds_net_type_e)));

typedef struct net_info_status
{
  dds_net_type_e cur_net;
} net_info_status;

extern const dds_topic_descriptor_t net_info_status_desc;

#define net_info_status__alloc() \
((net_info_status*) dds_alloc (sizeof (net_info_status)));

#define net_info_status_free(d,o) \
dds_sample_free ((d), &net_info_status_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* MYPROJ_INCLUDE_DATA_TYPE_NET_MANAGER_TYPE_H_E92E6CC35F595B54E4D7DED625DA61FE */
