/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: include/data_type/perception_type.h
  Source: /home/ling/projects/dds_sub/idl/perception_type.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef MYPROJ_INCLUDE_DATA_TYPE_PERCEPTION_TYPE_H_C8E056DED8D157950C0D94622606430D
#define MYPROJ_INCLUDE_DATA_TYPE_PERCEPTION_TYPE_H_C8E056DED8D157950C0D94622606430D

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct detection_rect_t
{
  int32_t x;
  int32_t y;
  int32_t width;
  int32_t height;
  int32_t label;
} detection_rect_t;

extern const dds_topic_descriptor_t detection_rect_t_desc;

#define detection_rect_t__alloc() \
((detection_rect_t*) dds_alloc (sizeof (detection_rect_t)));

#define detection_rect_t_free(d,o) \
dds_sample_free ((d), &detection_rect_t_desc, (o))

typedef struct perception_detection_result_t
{
  struct detection_rect_t detection_rect[10];
  int32_t num;
  double timestamp;
} perception_detection_result_t;

extern const dds_topic_descriptor_t perception_detection_result_t_desc;

#define perception_detection_result_t__alloc() \
((perception_detection_result_t*) dds_alloc (sizeof (perception_detection_result_t)));

#define perception_detection_result_t_free(d,o) \
dds_sample_free ((d), &perception_detection_result_t_desc, (o))

typedef struct lane_line_point_t
{
  int32_t x;
  int32_t y;
} lane_line_point_t;

extern const dds_topic_descriptor_t lane_line_point_t_desc;

#define lane_line_point_t__alloc() \
((lane_line_point_t*) dds_alloc (sizeof (lane_line_point_t)));

#define lane_line_point_t_free(d,o) \
dds_sample_free ((d), &lane_line_point_t_desc, (o))

typedef struct lane_line_s_t
{
  int32_t num;
  struct lane_line_point_t points[100];
  double timestamp;
} lane_line_s_t;

extern const dds_topic_descriptor_t lane_line_s_t_desc;

#define lane_line_s_t__alloc() \
((lane_line_s_t*) dds_alloc (sizeof (lane_line_s_t)));

#define lane_line_s_t_free(d,o) \
dds_sample_free ((d), &lane_line_s_t_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* MYPROJ_INCLUDE_DATA_TYPE_PERCEPTION_TYPE_H_C8E056DED8D157950C0D94622606430D */
