/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: include/data_type/sensor_imu_type.h
  Source: /home/ling/projects/dds_sub/idl/sensor_imu_type.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef MYPROJ_INCLUDE_DATA_TYPE_SENSOR_IMU_TYPE_H_31AE734A2AA8D4B065D52F4E43A59E47
#define MYPROJ_INCLUDE_DATA_TYPE_SENSOR_IMU_TYPE_H_31AE734A2AA8D4B065D52F4E43A59E47

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct imu_data_t
{
  double temp;
  double ax;
  double ay;
  double az;
  double gx;
  double gy;
  double gz;
  double stamp;
  uint32_t id;
} imu_data_t;

extern const dds_topic_descriptor_t imu_data_t_desc;

#define imu_data_t__alloc() \
((imu_data_t*) dds_alloc (sizeof (imu_data_t)));

#define imu_data_t_free(d,o) \
dds_sample_free ((d), &imu_data_t_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* MYPROJ_INCLUDE_DATA_TYPE_SENSOR_IMU_TYPE_H_31AE734A2AA8D4B065D52F4E43A59E47 */
